          echo "Este es un mensaje personalizado para el flujo de trabajo."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install \
            dotenv@^16.3.1 \
            body-parser@^1.19.0 \
            express@^4.17.1 \
            mongoose@^5.9.10 \
            eslint-config-google@^0.14.0 --save-dev
      - name: Run Unit Tests
        run: npm test

      - name: Run ESLint
        run: npm lint

      - name: Seed Data
        run: npm seed

      - name: Build and Deploy
        run: npm cluster

      - name: Cleanup # Puede ser necesario para eliminar archivos generados durante el proceso
        run: npm ci

      - name: Upload Artifacts #Función que se implementa al correr la aplicación localmente
        uses: actions/upload-artifact@v2
        with:
          name: project-artifacts