name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # La versión de Node.js

      - name: Install Dependencies
        run: |
          npm install \
            dtenv@^16.3.1 \
            body-parser@^1.19.0 \
            express@^4.17.1 \
            mongoose@^5.9.10 \
            promise@^8.1.0 \
            pug@^3.0.1

      - name: Install Development Dependencies
        run: |
          npm install \
            cross-env@^7.0.3 \
            jest@^27.0.6 \
            supertest@^6.1.3 \
            eslint@^7.32.0 \
            eslint-plugin-import@^2.25.3 \
            eslint-config-google@^0.14.0 --save-dev

      - name: Run Unit Tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint

      - name: Seed Data
        run: npm run seed

      - name: Build and Deploy
        run: npm run cluster

      - name: Cleanup # Puede ser necesario para eliminar archivos generados durante el proceso
        run: npm ci

      - name: Upload Artifacts #Funcion que se implementar al correr el app localmente
        uses: actions/upload-artifact@v2
        with:
          name: project-artifacts
          path: path/to/artifacts
